This notebook is a hands on version of the deeplizard ' Deep Learning with Pytorch ' playlist. 

Using it to understand tesnors , in order to get a better  understanding of how to maipulate tensors  to create custom models . eg using a combo of CNN and LSTM for image captioning . 

In [0]:
!pip3 install torch torchvision

###Tensors

Tensors and index :

    index req             CS                     Math

    0                    number                scalar

    1                    array                 vector

    2                    2d- array             matrix

    n                    nd-array              nd-tensor


here index req specifies how many indices are required to access a particular element of a tensor

In [0]:
import numpy as np

In [3]:
# 1d - array - one index req
data = np.array([13,22,49,50,38])
print(data[2])

49


In [5]:
# 2d - matrix - 2 indices req
data = np.array([[11,23,34],
               [29,12,40],
               [58,39,20],
               [15,12,90]])

print(data[1][2])

40


In [8]:
# 3d-tensor - 3 indices req
data = np.array([
                  [
                    [11,22,33,21],
                    [98,12,34,1],
                    [28,12,34,54]
                  ],
                  [
                    [14,92,43,9],
                    [37,45,84,2],
                    [19,57,31,35]
                  ]
                ])
# 2 matrix od 3 rows and 2 cols
print(data.shape)

(2, 3, 4)


In [9]:
print(data[1][2][0])

19


In [11]:
# 4d tensor 

data = np.array([
                  [
                      [
                        [11,22,33,21],
                        [98,12,34,1],
                        [28,12,34,54]
                      ],
                      [
                        [14,92,43,9],
                        [37,45,84,2],
                        [19,57,31,35]
                      ]
                  ],
                  [
                      [
                        [23,22,30,31],
                        [9,13,24,12],
                        [8,14,34,5]
                      ],
                      [
                        [54,32,4,9],
                        [47,49,94,20],
                        [99,77,33,3]
                      ]
                  ],
                  [
                      [
                        [21,2,3,41],
                        [93,13,23,32],
                        [0,4,35,53]
                      ],
                      [
                        [52,22,4,9],
                        [57,43,99,30],
                        [99,77,33,32]
                      ]
                  ]
                  
                ])

# 3 axis each having 2 tensors each with each tensor being of shape 3rows 4cols
print(data.shape)

(3, 2, 3, 4)


In [13]:
# second axis -> first tensor -> third row -> second col = 14
print(data[1][0][2][1])

14


Tensor differs from dimensions of vecctor in vector space . The dimension of tensor does not tell us hoe many components exist within tensor.

If we have a 3d tensor from a 3d euclidean space , we have an ordered triple with 3 components (x,y,z)

A 3d tensor however can have many more than 3 components . eg the 2d tensor has 9 components 

        data = np.array([
                  [12,34,21],
                  [35,56,75],
                  [23,45,67]
                ])

### Rank , Axes and Shape of Tensor

Shape of a tensor contains all info about rank, axis and length of tensor

Rank -> Axes -> Shape 

all related to indices

Rank of a Tensor 

**Rank refers to the number of dimensions present within the tensor.** Eg Rank 2 tensor implies :
  
  Matrix
  
  2D Array
  
  2D tensor
  
 **Rank of a tensor tells how many indexes are required to access a specific element within the tensor .**
 
 

Axes Of A Tensor 

**Axis of a tenso is a specific dimension of a tensor.**

Eg - tensor of rank = 2 has 2 dimensions or 2 axes

Elements are said to run along an axis, the running is constrained by the length of each axis.

** Length of an Axis ** - tells us how many indexes are available along each axis


In [0]:
import torch

In [0]:

# Eg Tensor t has length 3 along first axis 
# and length 4 along second axis

t = torch.tensor([
    [25,39,19,89],
    [23,11,90,42],
    [43,28,79,24],
]);


Thus can access three index positions along the first axis

t[0]

t[1]

t[2]

and can access four index positions along the second axis

t[0][0] ,  t[1][0] , t[2][0]

t[0][1] , t[1][1] ,t[2][1] ,

t[0][2] ,t[1][2] ,t[2][2]

t[0][3] ,t[1][3] ,t[2][3] 

In [5]:
# acessing along the first axis gives a 1d tensor
t[1]

tensor([23, 11, 90, 42])

In [6]:
# accessing along first and second tensor gives a 0d tensor
t[1][2]

tensor(90)

In [8]:
# only accessing the second axis or second col
t[:,1]

tensor([39, 11, 28])

** The element of the last axis are numbers t[1][2]. Every other axis will contain n-dimensional array t[1] **

Shape of a Tensor

** shape is determined by the length of each axis , if we know the shape then we know the length of each axis => how many indexes are available**

In [9]:
t.shape

torch.Size([3, 4])

In [10]:
# shape of first axis
t.shape[0]

3

*** Rank - No of dimensions ***

*** Axis  - Specific dimension ***

*** Shape - Length along each axis ***

Reshaping Tensor

Reshaping  tesnsor does not change the underlying data of the tensor. It only modifies the way it is stored/represented/ grouped

It changes the shape ( length along each axis ) but maintains the same data underneath.



Eg .

Shape - 1x6

[1,2,3,4,5,6]

Shape - 6 x 1

[ 1,   
 2,   
 3,   
 4,   
 5,   
 6 ]  
 
 Shape - 2 x 3
 
  [  [1,2,3],  
     [4,5,6]  ]
     
 Shape - 3 x2
 
 [ [1,2],  
   [3,4],  
   [5.6]  ]

** -1 implies as long as necessary **

In [11]:
# ony one dimension given
t.reshape(1,-1)

tensor([[25, 39, 19, 89, 23, 11, 90, 42, 43, 28, 79, 24]])

In [12]:
t.shape

torch.Size([3, 4])

In [13]:
t.reshape(4,3)

tensor([[25, 39, 19],
        [89, 23, 11],
        [90, 42, 43],
        [28, 79, 24]])

In [14]:
# increasing the rank - 3d tensor
t.reshape(2,2,3)

tensor([[[25, 39, 19],
         [89, 23, 11]],

        [[90, 42, 43],
         [28, 79, 24]]])

In [15]:
# 4d tensor
t.reshape(1,2,3,2)

tensor([[[[25, 39],
          [19, 89],
          [23, 11]],

         [[90, 42],
          [43, 28],
          [79, 24]]]])

### CNN Tensor Input 

Shape of a tensor encodes all info about axes , rank and length


In case of Image tensor it is a Rank 4  tensor with shape [ batch_size , image_channel, height, width]

HxW = 28x28 or 224x224

image_channel = 1 in greyscale and 3 in RGB

channel , height , width represent one single image - [ channel, height,width]

eg - [3,28,28 ] colored image with 3 channel RGB , to access red go to [0][23][10] red pixel value at width =10 and height=23

batch_size - allows us to work with multiple images at the same time . Eg - access green pixel from second image in batch at height =20 and width =15

t[2][1][20][15]


** Convolution ** - changes the shape and underlying data inside a tensor

It changes the height,width and color channels inside the tensor

3 filters will output 3 channels after a convolution ( even for a greyscale image )

One image is passed by 3 filters each producing a feature map

[1,1,28,28]  --> [1,3,28,28] ( feature maps )

Feature Map -> filter channel + input color channel  ( the output channels created from the convolutions)

### Pytorch Tensors

In [0]:
import torch 
import numpy as np

In [5]:
# Create an empty tensor
t = torch.Tensor()
type(t)

torch.Tensor

In [6]:
# default type is torch.float32
print(t.dtype)
# default device is cpu
print(t.device)
# default layout is strided
print(t.layout)

torch.float32
cpu
torch.strided


** Each tensor dtype has a cpu and gpu version and both are not compatible with each other , thus any calculation must occur between tensors of same dtype **

Eg - dtype = ** torch.float32  ->  torch.FloatTensor (cpu )  & torch.cuda.FloatTensor (gpu) **

In [8]:
# creating a gpu device
# 0 is the index of gpu. In multi gpu systems it can take more values

device = torch.device('cuda:0')
device

device(type='cuda', index=0)

** Takeaways **

* Tensor contain data of a uniform type ( dtype )
* Tensor computations between tensors depend on dtype and device 

There are 4 ways of creating torch tensors

In [9]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [10]:
# First is class method (capital Tensor ), it defaults the data to float
t1 = torch.Tensor(data);t1

tensor([1., 2., 3.])

In [11]:
# second is the functional version ( lowercase tensor ), it keeps the data as it is 
t2 = torch.tensor(data);t2

tensor([1, 2, 3])

In [12]:
# third is a method to create tensor , it also keeps the data type same
t3 = torch.as_tensor(data);t3

tensor([1, 2, 3])

In [13]:
# forth is another method to convert numpy arrays to tensors , keeping the same data type
t4 = torch.from_numpy(data);t4

tensor([1, 2, 3])

Other methods of initializing tensors such as identity, ones ,zero and random

In [14]:
# create an identity tensor , returns a 2D tensor with n rows and cols
t1 = torch.eye(3);t1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
# create a tensor of ones , takes a shape of tensor
t2 = torch.ones([2,2,2]);t2

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [18]:
# Create a tensor of zeros , takes a shape as input 
t3 = torch.zeros([2,3,2]);t3

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [20]:
# Create a tensor of random values , takes a shape as input
t4 = torch.rand([2,3,4]);t4

tensor([[[0.2023, 0.0633, 0.9448, 0.2953],
         [0.8125, 0.2100, 0.3645, 0.5333],
         [0.2097, 0.3086, 0.3539, 0.1787]],

        [[0.5748, 0.2957, 0.9695, 0.2538],
         [0.6716, 0.8465, 0.2034, 0.0762],
         [0.6287, 0.5249, 0.9280, 0.2362]]])

### Pytorch Tensors : Best options 

Differences in tensor creation 

torch.Tensor ( ) is a constructor of torch.Tensor class 

torch.tensor() is a factory function that constructs torch.Tensor objecrs and returns to the caller

** Factory functions can return a objects of varying prototype or class ** 

thus the tensor function has more configuration options like dtype etc.

In [22]:
# default dtype is the one that is created by the constructor
torch.get_default_dtype()

torch.float32

In [24]:
# factory functions can do type inference ie dtype is inferred based on the incoming data
data = np.array([1,2,3])
torch.tensor(data).dtype

torch.int64

In [25]:
# can also provide a dtype in the function
torch.tensor(data,dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

** Sharing Memory for performance : Copy vs Share **

      Share Data                Copy Data
      torch.as_tensor()         torch.Tensor()
      torch.from_numpy()        torch.tensor()
      
torch.as_tensor and torch.from_numpy both share the memory location with the underlying data . If the parent data is changed , then the tensor will also change.

In [0]:
data = np.array([1,2,3])

t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [28]:
t1,t2,t3,t4

(tensor([1., 2., 3.]), tensor([1, 2, 3]), tensor([1, 2, 3]), tensor([1, 2, 3]))

In [0]:
# changing data 
data[0] = 5
data[1] = 4
data[2] = 9


In [30]:
t1,t2,t3,t4

(tensor([1., 2., 3.]), tensor([1, 2, 3]), tensor([5, 4, 9]), tensor([5, 4, 9]))

 Choosing b/w      *torch.Tensor*     and        *torch.tensor*      ->      **torch.tensor** as better customization 
 
 Choosing b/w    *torch.as_tensor *  and  * torch.from_numpy*  -> **torch.as_tensor**  as it can also take in lists as inputs while from_numpy can only work  with numpy arrays

** Important Caveats **

* numpy.ndarray objects are allocated on CPU , the as_tensor function must copy data from CPU to GPU when GPU is being used
* Memory sharing of as_tensor does not work with built in Python data structures like lists
* The as_tensor call requires developer knowledge of the sharing feature.
* Performance improvement will be greater when there are lot of back and forth operations b/w numpy.ndarray and tensor objects. For single load operations , performance gain will be not much.

### Flatten , Reshape ,Squeeze and Concat

In [0]:
import torch

** Tensor operation types: **

* Reshaping (important)
* Element-wise
* Reduction
* Access
  


In [0]:
# reshaping

t = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
],dtype=torch.float32)

In [4]:
# Determine the shape of the tensor 
t.shape

torch.Size([3, 4])

In [5]:
# also can use size() to determine shape
t.size()

torch.Size([3, 4])

** Rank of tensor = no. of axis = length of shape **

In [6]:
# rank of this tensor =2
len(t.shape)

2

** Number of elements in tensor = product of shape values **

In [7]:
# creating a tensor of the shape object 
# returning the product of it
torch.tensor(t.shape).prod()

tensor(12)

In [8]:
# There is a dedicated function numel for it as well
# number of elements
t.numel()

12

 #### Reshaping only changes the shape of the tensor but the underlying data remains the same 

All reshapes of same rank for tensor t  ( must be a factor of 12 )

In [9]:
t.reshape([1,12])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [10]:
t.reshape([2,6])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [11]:
t.reshape([3,4])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [12]:
t.reshape([4,3])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [13]:
t.reshape([6,2])

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [14]:
t.reshape([12,1])

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

** Can also increase the rank of the tensor , but the number of elements should be 12 **

In [15]:
t.reshape([2,3,2])

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

#### Changing shape by sqeezing and unsqueezing

** Squeezing ** - removes the dimensions or axes that have a length of 1

** Unsqueezing ** - adds a dimension with length of one 

In [16]:
t

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [18]:
t.reshape([1,12]) , t.reshape([1,12]).shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [19]:
# no effect as all all axes >1
t.reshape([3,4]).squeeze()

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [20]:
# removes one axis -> look at the number of []
t.reshape([1,12]).squeeze() , t.reshape([1,12]).squeeze().shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [22]:
# Unsqueeze 
# needs a dimension where to add a new dimension to
t.reshape([3,4]).unsqueeze(dim=0)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]])

In [26]:
# added a dimension to the lowermost value
t.reshape([3,4]).unsqueeze(dim=2)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]])

In [32]:
# whole list inside []
print(t.reshape([1,12]).squeeze().unsqueeze(dim=-2))
# each element inside a []
print(t.reshape([1,12]).squeeze().unsqueeze(dim=-1))
# whole list inside []
print(t.reshape([1,12]).squeeze().unsqueeze(dim=-2))
# each element inside a []
print(t.reshape([1,12]).squeeze().unsqueeze(dim=-1))


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])


#### Flatten - to remove all dimensions except for one 

** if passed -1 as a second argument , converts the tensor into a single long tensor **

In [33]:
t.reshape(1,-1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [34]:
# Still have 2 [] , to remove one and create a 1d tensor use squeeze
t.reshape(1,-1).squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [0]:
def flatten(t):
  t = t.reshape(1,-1)
  t = t.squeeze()
  return t

In [0]:
temp = torch.ones([2,3,4])

In [37]:
temp

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [38]:
flatten(temp)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])

** Flatten is used in CNN to get to final fully connected layers ** 

Can also flatten only specific parts of tensor eg have a tensor of shape [2,1,28,28] ( batch of 2 ; 28x28 greyscale images )

Specifically flatten to [2,1,784] -> [2,784]

#### Concatenating Tensors 

Using cat() method . The dim given determines how the tensors are concatenate 

In [0]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype=torch.float32)

t2 = torch.tensor([
    [5,6],
    [7,8]
],dtype=torch.float32)

In [47]:
# Concatinating row wise axis =0 t2 comes below t1
torch.cat((t1,t2),dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [48]:
# Concatinating column wise axis =1 , t2 comes aside t1
torch.cat((t1,t2),dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [49]:
# Checking the shapes of the two operations 
torch.cat((t1,t2),dim=0).shape , torch.cat((t1,t2),dim=1).shape

(torch.Size([4, 2]), torch.Size([2, 4]))

In [50]:
# Testing higher rank tensors 
t3 = torch.ones([3,2,2])
t3

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [53]:
# incompatible as no of dimensions do not match
torch.cat((t3,t1),dim=2)

RuntimeError: ignored

In [0]:
# can be done with a view
x = torch.rand(2, 400, 1, 1)
y = torch.rand(2, 400, 2, 2)
z = torch.rand(2, 400, 4, 4)
x = x.view(x.size(0), -1)
y = y.view(y.size(0), -1)
z = z.view(z.size(0), -1)

out = torch.cat([x, y, z], dim=1)

In [56]:
out.shape, x.size(0)

(torch.Size([2, 8400]), 2)

### Tensor Flattening for CNN

Flattening a specific axis in a tensor

In [0]:
import torch

# Eg a bunch of 4x4 images 

t1 = torch.tensor([[
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
]])

t2 = torch.tensor([[
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
]])

t3 = torch.tensor([[
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
]])

Create  a stack of these images using **torch.stack**

In [4]:
t = torch.stack((t1,t2,t3))

t.shape

torch.Size([3, 1, 4, 4])

The tensor is now a batch of 3 greyscale images , each of width=4 and height=4



    [ Batch
      [ Channel
         [ Height
            Width[1, 1, 1, 1],
            [1, 1, 1, 1],
            [1, 1, 1, 1],
            [1, 1, 1, 1]
        ]
    ],
    [
        [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2]
        ]
    ],
    [
        [
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3]
        ]
    ]
]

In [5]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [6]:
# Accessing first image 
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [7]:
# Accessing first color channel of first image 
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [8]:
#Accessing first row of first color channel of first image 
t[0][0][0]

tensor([1, 1, 1, 1])

In [9]:
# Accessing first pixel value of first row of first color channel of first image 
t[0][0][0][0]

tensor(1)

#### Flattening the tensor batch

In [10]:
# Using reshape 
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
# Using reshape with one param
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [12]:
# Using view and numel
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Pytorch also has a flatten method that flattens to a 1d tensor or can even flatten a particular axis

In [14]:
# flatten to a 1d tensor , unable to distinguish b/w different image pixels
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [15]:
# Eg want to flatten the color channel
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [16]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

** start_dim is the axis from where we want to start flattening out the tensor **

In [17]:
t.flatten(start_dim=0)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [18]:
t.flatten(start_dim=2)

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]])

In [19]:
t.flatten(start_dim=3)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [20]:
# Using reshape to flatten to images 
t.reshape((3,16))

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

### Broadcasting and Element-wise operations

Element wise operation operates on correspoding elements between tensors.

** Corresponding element ** - Two elements are called corresponding if they share the same index position within tensors

**Thus for element wise operations two tensors must have the same shape**

Element-wise <=> Component-wise <=> Point-wise

In [0]:
import torch 
import numpy as np

t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype=torch.float32)

t2 =  torch.tensor([
    [9,8],
    [7,6]
],dtype=torch.float32)



In [4]:
# Corresponding elements
t1[0][1], t2[0][1]

(tensor(2.), tensor(8.))

** Arithmetic operations are Element-wise **

In [6]:
print(t1+2)
print(t1-2)
print(t1*2)
print(t1/2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [8]:
# Can also use the tensor built in methods
print(t1.add(2))
print(t1.sub(2))
print(t1.mul(2))
print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


** scalar value 2 ** is used in all the operations?

#### Broadcasting Tensors 

Broadcasting is a concept whose implementation allows us to add scalars to higer dimensional tensors

It converts the scalar into tensor of same shape 

** Especially useful during data preprocessing and data normalization **

In [9]:
# value,shape
# Scalar transformed to a rank 2 tensor like t1
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [10]:
# Thus t1 + 2 is really in implementation
t1 + torch.tensor(
                  np.broadcast_to(2,t1.shape),
                  dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [0]:
# Trickier example
t1 = torch.tensor([
    [1,1],
    [1,1]
],dtype=torch.float32)

t2 = torch.tensor([2,4],dtype=torch.float32)

In [12]:
# t2 of shape [2] braodcasted to [2,2]
t1+t2

tensor([[3., 5.],
        [3., 5.]])

In [16]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

#### Comparison Operations 

Returns a new tensor of same shape containing 0 (false) and 1(true), after comparing corresponding elements

In [0]:
t = torch.tensor([
    [1,2,4],
    [5,3,9],
    [8,6,7]
],dtype=torch.float32)

In [18]:
t>5

tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [19]:
# Using Pytorch functions 

# equal
print(t.eq(3))

# >=
print(t.ge(4))

# >
print(t.gt(5))

# <
print(t.lt(8))

# <=
print(t.le(7))

tensor([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]], dtype=torch.uint8)
tensor([[0, 0, 1],
        [1, 0, 1],
        [1, 1, 1]], dtype=torch.uint8)
tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 1, 1]], dtype=torch.uint8)
tensor([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]], dtype=torch.uint8)
tensor([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]], dtype=torch.uint8)


In [20]:
# All the comparison operations use broadcasting
t <=torch.tensor(
      np.broadcast_to(7,t.shape),
      dtype=torch.float32)

tensor([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]], dtype=torch.uint8)

In [21]:
# which is equivlent to 
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
],dtype=torch.float32)

tensor([[1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]], dtype=torch.uint8)

#### Element Wise operations using functions

Functions like abs, sqrt etcc applied to each element

In [22]:
t.abs()

tensor([[1., 2., 4.],
        [5., 3., 9.],
        [8., 6., 7.]])

In [23]:
t.neg()

tensor([[-1., -2., -4.],
        [-5., -3., -9.],
        [-8., -6., -7.]])

In [24]:
t.sqrt()

tensor([[1.0000, 1.4142, 2.0000],
        [2.2361, 1.7321, 3.0000],
        [2.8284, 2.4495, 2.6458]])

### ArgMax, Reduction and Access  Operations 

** Reduction operation on a tensor is operation that reduces the number of elements contained within a tensor **

Reduction operations in general allow to compute the aggregate across data structures

In [0]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

In [26]:
# Reducing to sum
t.sum()

tensor(8.)

In [27]:
# Sum reduced the 9 elements inside the tensor into  a single one 
t.numel(), t.sum().numel()

(9, 1)

In [28]:
# Other common reduction operations
print(t.prod())
print(t.mean())
print(t.std())

tensor(0.)
tensor(0.8889)
tensor(1.1667)


** Reducing Tensors by axes ** 

Reduction can reduce to tensors of size > 1 as well

In [0]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [31]:
# Can sum across any dimension 0 (col) , 1 (row)
t.shape

torch.Size([3, 4])

In [32]:
# across dim=0 ie cols
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [33]:
# across dim=1 ie rows
t.sum(dim=1)

tensor([ 4.,  8., 12.])

** Argmax returns the index location of the max value inside tensor **

In [0]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype=torch.float32)

In [35]:
# Max value in t =5 ,
t.max()

tensor(5.)

In [37]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

** Argmax returning the index after flattening the tensor **

In [39]:
# index of max =5 in flattened tensor =11
t.argmax()

tensor(11)

**Using Argmax with axes**

In [41]:
# max across the columns , two tensors returned , max value across cols and the index of those values 
t.max(dim=0)

(tensor([4., 3., 3., 5.]), tensor([2, 1, 1, 2]))

In [42]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [43]:
# max across rows and their indices
t.max(dim=1)

(tensor([2., 3., 5.]), tensor([3, 1, 3]))

In [44]:
t.argmax(dim=1)

tensor([3, 1, 3])

** Access value inside tensor using .item()  only for single value **

** Use .toList() or .numpy() to create list /array for multiple values **

In [46]:
t.mean()

tensor(1.5000)

In [47]:
t.mean().item()

1.5

In [48]:
# can also create a list or a numpy array
t.mean(dim=0)

tensor([1.6667, 1.0000, 1.0000, 2.3333])

In [50]:
t.mean(dim=0).item()

ValueError: ignored

In [51]:
t.mean(dim=0).tolist()

[1.6666666269302368, 1.0, 1.0, 2.3333332538604736]

In [52]:
t.mean(dim=0).numpy()

array([1.6666666, 1.       , 1.       , 2.3333333], dtype=float32)